### ISSUE TITLE
Start error

### ISSUE THREAD

**Issue by salmazov** [tylermcginnis/rrssr#5]
` npm run start

> rr-ssr-gists@1.0.0 start /home/ubuntu/workspace/ssr/rrssr
> webpack -w & nodemon server.js

[nodemon] 1.18.6
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `node server.js index.js`
module.js:471
    throw err;
    ^

Error: Cannot find module '/home/ubuntu/workspace/ssr/rrssr/index.js'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:504:3
[nodemon] app crashed - waiting for file changes before starting...

Webpack is watching the files…

[nodemon] restarting due to changes...
[nodemon] starting `node server.js index.js`
[nodemon] restarting due to changes...
[nodemon] starting `node server.js index.js`
module.js:471
    throw err;
    ^

Error: Cannot find module '/home/ubuntu/workspace/ssr/rrssr/index.js'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:504:3
[nodemon] app crashed - waiting for file changes before starting...
[BABEL] Note: The code generator has deoptimised the styling of "/home/ubuntu/workspace/ssr/rrssr/node_modules/react-dom/cjs/react-dom.development.js" as it exceeds the max of "500KB".
[nodemon] restarting due to changes...
[nodemon] starting `node server.js index.js`
Hash: bff9cea1ec1b7c6cae060ba71515fe741766f334
Version: webpack 3.12.0
Child
    Hash: bff9cea1ec1b7c6cae06
    Time: 16990ms
        Asset     Size  Chunks                    Chunk Names
    bundle.js  1.04 MB       0  [emitted]  [big]  main
      [24] ./src/browser/index.js 546 bytes {0} [built]
      [35] ./src/shared/App.js 3.85 kB {0} [built]
      [36] ./src/shared/routes.js 726 bytes {0} [built]
      [37] ./src/shared/Home.js 390 bytes {0} [built]
      [38] ./src/shared/Grid.js 4.67 kB {0} [built]
      [39] ./src/shared/api.js 854 bytes {0} [built]
      [68] ./src/shared/Navbar.js 1.04 kB {0} [built]
      [69] ./src/shared/NoMatch.js 391 bytes {0} [built]
        + 62 hidden modules
Child
    Hash: 0ba71515fe741766f334
    Time: 2860ms
        Asset     Size  Chunks             Chunk Names
    server.js  17.9 kB       0  [emitted]  main
       [2] ./src/shared/routes.js 726 bytes {0} [built]
       [3] ./src/server/index.js 2.22 kB {0} [built]
       [8] ./src/shared/App.js 3.85 kB {0} [built]
       [9] ./src/shared/Home.js 390 bytes {0} [built]
      [10] ./src/shared/Grid.js 4.67 kB {0} [built]
      [11] ./src/shared/api.js 854 bytes {0} [built]
      [13] ./src/shared/Navbar.js 1.04 kB {0} [built]
      [14] ./src/shared/NoMatch.js 391 bytes {0} [built]
        + 7 hidden modules
module.js:471
    throw err;
    ^

Error: Cannot find module '/home/ubuntu/workspace/ssr/rrssr/index.js'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:504:3
[nodemon] app crashed - waiting for file changes before starting...`

**Comment by supachaic** [comment]
I found same issue and solve by changing "main" in package.json from "index.js" to "server.js".
Then revise "start" scripts as below.

------ package.json -----
"main": "server.js",
  "scripts": {
    "start": "webpack -w & nodemon",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
----- the rest of file -----
